version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
        - checkout
        - run:
            name: Setup the Virtual Environment
            command: make venv
        - run:
            name: Install core utilities
            command: make install
        - run:
            name: Install dependencies
            command: make deps
        - run:
            name: Install Panther CLI
            command: pipenv run -- pip3 install -e .
        - run:
            name: CLI Tests
            command: make ci && make integration
