on: [push, pull_request]

permissions:
  contents: read

jobs:
  mypy:
    if: ${{ github.actor != 'panther-bot-automation' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: 3.11
          cache: 'poetry'
      - name: Install dependencies
        run: poetry sync
      - name: Run mypy
        run: poetry run mypy panther_analysis_tool

  bandit:
    if: ${{ github.actor != 'panther-bot-automation' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: 3.11
          cache: 'poetry'
      - name: Install dependencies
        run: poetry sync
      - name: Run bandit
        run: poetry run bandit -r panther_analysis_tool

  pylint:
    if: ${{ github.actor != 'panther-bot-automation' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: 3.11
          cache: 'poetry'
      - name: Install dependencies
        run: poetry sync
      - name: Run pylint
        run: poetry run pylint panther_analysis_tool

  test:
    if: ${{ github.actor != 'panther-bot-automation' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: 3.11
          cache: 'poetry'
      - name: Install dependencies
        run: poetry sync
      - name: Run tests
        run: poetry run pytest --cov=panther_analysis_tool --cov-report=html

  integration:
    if: ${{ github.actor != 'panther-bot-automation' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: 3.11
          cache: 'poetry'
      - name: Install dependencies
        run: poetry sync
      - name: Run fixture integration test
        run: poetry run panther_analysis_tool test --path tests/fixtures/detections/valid_analysis
      - name: Shallow clone panther-analysis
        run: git clone --depth 1 https://github.com/panther-labs/panther-analysis.git
      - name: Cache pipenv dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ~/.local/share/virtualenvs
          key: pipenv-${{ hashFiles('panther-analysis/Pipfile.lock') }}
      - name: Install pipenv
        run: pip install pipenv
      - name: Run panther-analysis integration tests
        run: |
          cd panther-analysis
          pipenv lock
          pipenv requirements | grep -v 'panther-analysis-tool==' > requirements.ci.txt
          pipenv install -r requirements.ci.txt
          pipenv install -e ..
          pip install schema==0.7.5
          pipenv run panther_analysis_tool --version
          pipenv run panther_analysis_tool test --path .
