name: Publish Release and pypi

on:
  workflow_dispatch:

jobs:
  publish_github_release_and_pypi:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install pip and pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Release and publish to PyPI
      run: |
        export NEW_VERSION=$(cat VERSION)
        git config user.name "dac-bot"
        git config user.email "dac-bot@panther.com"
        gh release create v$NEW_VERSION -t v$NEW_VERSION
        make pypi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
